// <auto-generated> from Localization/Strings.json
// Do not edit by hand. Keys.X.Y avoid key typos in code.
// CẢNH BÁO: KHÔNG chạy .agents-workflow/strings/build_catalog.py — script cũ (2 gen trước) sẽ GHI ĐÈ bản dịch zh/ru/ja của Strings.json thành "---". Keys.cs được thêm tay theo pattern; khi có script regen an toàn thì thay thế.
namespace Printonator.UI.Localization;

public static class Keys
{
    public static class About
    {
        public const string AuthorLink = "About.AuthorLink";
        public const string AuthorLinkSuffix = "About.AuthorLinkSuffix";
        public const string AuthorText = "About.AuthorText";
        public const string AuthorTitle = "About.AuthorTitle";
        public const string ChangeLogFail = "About.ChangeLogFail";
        public const string ChangeLogLatest = "About.ChangeLogLatest";
        public const string ChangeLogLoading = "About.ChangeLogLoading";
        public const string ChangeLogNetworkFail = "About.ChangeLogNetworkFail";
        public const string ChangeLogTitle = "About.ChangeLogTitle";
        public const string CloseButton = "About.CloseButton";
        public const string ContactTitle = "About.ContactTitle";
        public const string EmailText = "About.EmailText";
        public const string GitHubLabel = "About.GitHubLabel";
        public const string GitHubSuffix = "About.GitHubSuffix";
        public const string LanguageLabel = "About.LanguageLabel";
        public const string LanguageRestartPrompt = "About.LanguageRestartPrompt";
        public const string LanguageRestartTitle = "About.LanguageRestartTitle";
        public const string LanguageTooltip = "About.LanguageTooltip";
        public const string LicenseText = "About.LicenseText";
        public const string LicenseTitle = "About.LicenseTitle";
        public const string SecurityNote = "About.SecurityNote";
        public const string VersionText = "About.VersionText";
        public const string WindowTitle = "About.WindowTitle";
    }

    public static class Approve
    {
        public const string Title = "Approve.Title";
        public const string ApproveButton = "Approve.ApproveButton";
        public const string RejectButton = "Approve.RejectButton";
        public const string ApproveAll = "Approve.ApproveAll";
        public const string RejectAll = "Approve.RejectAll";
        public const string QueueTitle = "Approve.QueueTitle";
        public const string NonePending = "Approve.NonePending";
        public const string ApproveAllConfirm = "Approve.ApproveAllConfirm";
        public const string RejectAllConfirm = "Approve.RejectAllConfirm";
        public const string ApprovedToast = "Approve.ApprovedToast";
        public const string RejectedToast = "Approve.RejectedToast";
    }

    public static class Banner
    {
        public const string ConfirmRePrint = "Banner.ConfirmRePrint";
        public const string ConfirmRePrintTitle = "Banner.ConfirmRePrintTitle";
        public const string FileAddError = "Banner.FileAddError";
        public const string FileNotFound = "Banner.FileNotFound";
        public const string FileOpenError = "Banner.FileOpenError";
        public const string NoFilesAfterSkip = "Banner.NoFilesAfterSkip";
        public const string NoFilesSelected = "Banner.NoFilesSelected";
        public const string PasteError = "Banner.PasteError";
        public const string PrintAllHint = "Banner.PrintAllHint";
        public const string PrinterScanError = "Banner.PrinterScanError";
        public const string PrinterScanHint = "Banner.PrinterScanHint";
        public const string PrinterUnresponsive = "Banner.PrinterUnresponsive";
        public const string PrinterUnresponsiveHint = "Banner.PrinterUnresponsiveHint";
        public const string SortError = "Banner.SortError";
        public const string UpdateChecksumFail = "Banner.UpdateChecksumFail";
        public const string UpdateConfirm = "Banner.UpdateConfirm";
        public const string UpdateConfirmTitle = "Banner.UpdateConfirmTitle";
        public const string UpdateDownloadFail = "Banner.UpdateDownloadFail";
        public const string UpdateLaunchFail = "Banner.UpdateLaunchFail";
    }

    public static class Common
    {
        public const string ApplyButton = "Common.ApplyButton";
        public const string CancelButton = "Common.CancelButton";
        public const string CheckUpdateButton = "Common.CheckUpdateButton";
        public const string FileFallback = "Common.FileFallback";
        public const string LatestVersionStatus = "Common.LatestVersionStatus";
        public const string LicenseText = "Common.LicenseText";
        public const string NativeErrFormat = "Common.NativeErrFormat";
        public const string OkButton = "Common.OkButton";
        public const string PagesCountSuffix = "Common.PagesCountSuffix";
        public const string PreviewErrorFormat = "Common.PreviewErrorFormat";
        public const string SectionInfoFormat = "Common.SectionInfoFormat";
        public const string SheetAll = "Common.SheetAll";
        public const string SheetLoading = "Common.SheetLoading";
        public const string VersionFormat = "Common.VersionFormat";
    }

    public static class Confirm
    {
        public const string Body = "Confirm.Body";
        public const string DoNotCloseWarning = "Confirm.DoNotCloseWarning";
        public const string PrintButton = "Confirm.PrintButton";
        public const string PrinterNote = "Confirm.PrinterNote";
        public const string Title = "Confirm.Title";
        public const string WindowTitle = "Confirm.WindowTitle";
    }

    public static class Done
    {
        public const string Checking = "Done.Checking";
        public const string ChecksumFail = "Done.ChecksumFail";
        public const string ContactText = "Done.ContactText";
        public const string DoneText = "Done.DoneText";
        public const string DoneTextEmpty = "Done.DoneTextEmpty";
        public const string DownloadFailed = "Done.DownloadFailed";
        public const string Downloading = "Done.Downloading";
        public const string Latest = "Done.Latest";
        public const string LaunchFail = "Done.LaunchFail";
        public const string LicenseText = "Done.LicenseText";
        public const string RateRequest = "Done.RateRequest";
        public const string RemoveCheck = "Done.RemoveCheck";
        public const string Title = "Done.Title";
        public const string UpdateConfirm = "Done.UpdateConfirm";
        public const string UpdateConfirmTitle = "Done.UpdateConfirmTitle";
        public const string VersionText = "Done.VersionText";
        public const string WindowTitle = "Done.WindowTitle";
    }

    public static class Error
    {
        public const string FileAddFailed = "Error.FileAddFailed";
        public const string FileNotFound = "Error.FileNotFound";
        public const string FileOpenFailed = "Error.FileOpenFailed";
        public const string NoFilesSelected = "Error.NoFilesSelected";
        public const string PasteFailed = "Error.PasteFailed";
        public const string PrinterScan = "Error.PrinterScan";
        public const string PrinterScanHint = "Error.PrinterScanHint";
        public const string SpoolerFailed = "Error.SpoolerFailed";
        public const string UpdateChecksum = "Error.UpdateChecksum";
        public const string UpdateDownload = "Error.UpdateDownload";
        public const string UpdateLaunch = "Error.UpdateLaunch";
    }

    public static class History
    {
        public const string HistorySaved = "History.HistorySaved";
    }

    public static class Main
    {
        public const string ActionAllFiles = "Main.ActionAllFiles";
        public const string ActionSelectedFiles = "Main.ActionSelectedFiles";
        public const string ActionThisBatch = "Main.ActionThisBatch";
        public const string AddFilesButton = "Main.AddFilesButton";
        public const string BannerCloseTooltip = "Main.BannerCloseTooltip";
        public const string BannerErrorFormat = "Main.BannerErrorFormat";
        public const string BannerRetryButton = "Main.BannerRetryButton";
        public const string BulkCountFormat = "Main.BulkCountFormat";
        public const string BulkFullText = "Main.BulkFullText";
        public const string BulkSettingsButton = "Main.BulkSettingsButton";
        public const string BulkSettingsTooltip = "Main.BulkSettingsTooltip";
        public const string BulkSummaryFormat = "Main.BulkSummaryFormat";
        public const string BulkSummaryTooltip = "Main.BulkSummaryTooltip";
        public const string ColError = "Main.ColError";
        public const string ColName = "Main.ColName";
        public const string ColNameTooltip = "Main.ColNameTooltip";
        public const string ColPages = "Main.ColPages";
        public const string ColPagesTooltip = "Main.ColPagesTooltip";
        public const string ColPrinter = "Main.ColPrinter";
        public const string ColSettings = "Main.ColSettings";
        public const string ColSettingsTooltip = "Main.ColSettingsTooltip";
        public const string ColStatus = "Main.ColStatus";
        public const string ColStatusTooltip = "Main.ColStatusTooltip";
        public const string CtxEdit = "Main.CtxEdit";
        public const string CtxEditPlural = "Main.CtxEditPlural";
        public const string CtxEditTooltip = "Main.CtxEditTooltip";
        public const string CtxItemSettings = "Main.CtxItemSettings";
        public const string CtxItemSettingsPlural = "Main.CtxItemSettingsPlural";
        public const string CtxItemSettingsTooltip = "Main.CtxItemSettingsTooltip";
        public const string CtxOpen = "Main.CtxOpen";
        public const string CtxOpenPlural = "Main.CtxOpenPlural";
        public const string CtxPageRange = "Main.CtxPageRange";
        public const string CtxPrint = "Main.CtxPrint";
        public const string CtxPrintPlural = "Main.CtxPrintPlural";
        public const string CtxRemove = "Main.CtxRemove";
        public const string CtxRemovePlural = "Main.CtxRemovePlural";
        public const string DropHighlightHint = "Main.DropHighlightHint";
        public const string DropHighlightTitle = "Main.DropHighlightTitle";
        public const string EmptyStateHint = "Main.EmptyStateHint";
        public const string EmptyStateTitle = "Main.EmptyStateTitle";
        public const string FolderLeafFallback = "Main.FolderLeafFallback";
        public const string FooterHintDefault = "Main.FooterHintDefault";
        public const string FooterHintSelection = "Main.FooterHintSelection";
        public const string FooterProgressFormat = "Main.FooterProgressFormat";
        public const string FooterStatsFormat = "Main.FooterStatsFormat";
        public const string InfoButton = "Main.InfoButton";
        public const string InfoTooltip = "Main.InfoTooltip";
        public const string NotifBadgeDone = "Main.NotifBadgeDone";
        public const string NotifBadgeError = "Main.NotifBadgeError";
        public const string NotifBadgeUpdate = "Main.NotifBadgeUpdate";
        public const string NotifCheckUpdate = "Main.NotifCheckUpdate";
        public const string NotifCheckUpdateTooltip = "Main.NotifCheckUpdateTooltip";
        public const string NotifEmpty = "Main.NotifEmpty";
        public const string NotifTitle = "Main.NotifTitle";
        public const string PagesAll = "Main.PagesAll";
        public const string PagesAllLower = "Main.PagesAllLower";
        public const string PagesAllRadio = "Main.PagesAllRadio";
        public const string PagesCellTooltip = "Main.PagesCellTooltip";
        public const string PagesCloseButton = "Main.PagesCloseButton";
        public const string PagesCustomRadio = "Main.PagesCustomRadio";
        public const string PagesCustomTooltip = "Main.PagesCustomTooltip";
        public const string PagesPopupTitle = "Main.PagesPopupTitle";
        public const string PagesSyntax = "Main.PagesSyntax";
        public const string PrintMainBtnAll = "Main.PrintMainBtnAll";
        public const string PrintMainBtnPause = "Main.PrintMainBtnPause";
        public const string PrintMainBtnResume = "Main.PrintMainBtnResume";
        public const string PrintMainBtnSelected = "Main.PrintMainBtnSelected";
        public const string PrintMainButton = "Main.PrintMainButton";
        public const string PrintSettingsButton = "Main.PrintSettingsButton";
        public const string PrintSettingsTooltip = "Main.PrintSettingsTooltip";
        public const string PrinterDefaultName = "Main.PrinterDefaultName";
        public const string PrinterReminderText = "Main.PrinterReminderText";
        public const string PrinterReminderTooltip = "Main.PrinterReminderTooltip";
        public const string PrinterStatusDotNoPrinter = "Main.PrinterStatusDotNoPrinter";
        public const string PrinterStatusReady = "Main.PrinterStatusReady";
        public const string PrinterStatusTooltip = "Main.PrinterStatusTooltip";
        public const string PrinterStatusWithDetail = "Main.PrinterStatusWithDetail";
        public const string PrinterToolbarDefault = "Main.PrinterToolbarDefault";
        public const string PrintersButton = "Main.PrintersButton";
        public const string ManagePresetsButton = "Main.ManagePresetsButton";
        public const string ReloadedBadge = "Main.ReloadedBadge";
        public const string SearchTooltip = "Main.SearchTooltip";
        public const string SelectAllTooltip = "Main.SelectAllTooltip";
        public const string SettingsCellTooltip = "Main.SettingsCellTooltip";
        public const string SheetComboTooltip = "Main.SheetComboTooltip";
        public const string SheetLabel = "Main.SheetLabel";
        public const string WatchButton = "Main.WatchButton";
        public const string WindowTitle = "Main.WindowTitle";
    }

    public static class Mode
    {
        public const string ModeLabel = "Mode.ModeLabel";
        public const string LiteLabel = "Mode.LiteLabel";
        public const string FullLabel = "Mode.FullLabel";
        public const string RestartPrompt = "Mode.RestartPrompt";
    }

    public static class Notify
    {
        public const string BatchDone = "Notify.BatchDone";
        public const string BatchStopped = "Notify.BatchStopped";
        public const string BatchStoppedDetail = "Notify.BatchStoppedDetail";
        public const string UpdateAvailable = "Notify.UpdateAvailable";
        public const string UpdateLatest = "Notify.UpdateLatest";
    }

    public static class Option
    {
        public const string AllPages = "Option.AllPages";
        public const string AsDocument = "Option.AsDocument";
        public const string AsPrinter = "Option.AsPrinter";
        public const string Booklet = "Option.Booklet";
        public const string ByDocuments = "Option.ByDocuments";
        public const string ByPages = "Option.ByPages";
        public const string Color = "Option.Color";
        public const string EvenPages = "Option.EvenPages";
        public const string Fill = "Option.Fill";
        public const string Fit = "Option.Fit";
        public const string Grayscale = "Option.Grayscale";
        public const string Landscape = "Option.Landscape";
        public const string LongEdge = "Option.LongEdge";
        public const string OddPages = "Option.OddPages";
        public const string Original = "Option.Original";
        public const string PaperAsDocument = "Option.PaperAsDocument";
        public const string PaperAsPrinter = "Option.PaperAsPrinter";
        public const string PerSheet1 = "Option.PerSheet1";
        public const string PerSheet16 = "Option.PerSheet16";
        public const string PerSheet2 = "Option.PerSheet2";
        public const string PerSheet4 = "Option.PerSheet4";
        public const string PerSheet6 = "Option.PerSheet6";
        public const string PerSheet9 = "Option.PerSheet9";
        public const string Portrait = "Option.Portrait";
        public const string QualityDraft = "Option.QualityDraft";
        public const string QualityHigh = "Option.QualityHigh";
        public const string QualityLow = "Option.QualityLow";
        public const string QualityMedium = "Option.QualityMedium";
        public const string ShortEdge = "Option.ShortEdge";
        public const string Shrink = "Option.Shrink";
        public const string Simplex = "Option.Simplex";
        public const string TrayAsPrinter = "Option.TrayAsPrinter";
        public const string TrayUnknown = "Option.TrayUnknown";
        public const string Zoom = "Option.Zoom";
    }

    public static class Persist
    {
        public const string RestoredToast = "Persist.RestoredToast";
    }

    public static class Preset
    {
        public const string ManageTitle = "Preset.ManageTitle";
        public const string NewName = "Preset.NewName";
        public const string ExportSuccess = "Preset.ExportSuccess";
        public const string ImportSuccess = "Preset.ImportSuccess";
        public const string ExportButton = "Preset.ExportButton";
        public const string ExportEmpty = "Preset.ExportEmpty";
        public const string ImportButton = "Preset.ImportButton";
        public const string ImportEmpty = "Preset.ImportEmpty";
        public const string ExportCount = "Preset.ExportCount";
        public const string ExportFail = "Preset.ExportFail";
        public const string FileDialogFilter = "Preset.FileDialogFilter";
        public const string RenameButton = "Preset.RenameButton";
        public const string DeleteButton = "Preset.DeleteButton";
        public const string ApplyButton = "Preset.ApplyButton";
        public const string NoneSelected = "Preset.NoneSelected";
        public const string EmptyList = "Preset.EmptyList";
        public const string Deleted = "Preset.Deleted";
        public const string Renamed = "Preset.Renamed";
        public const string Applied = "Preset.Applied";
    }

    public static class Printers
    {
        public const string AvailableBadge = "Printers.AvailableBadge";
        public const string BackButton = "Printers.BackButton";
        public const string Header = "Printers.Header";
        public const string HeaderSubDefault = "Printers.HeaderSubDefault";
        public const string HeaderSubError = "Printers.HeaderSubError";
        public const string HeaderSubSummary = "Printers.HeaderSubSummary";
        public const string OfflineBanner = "Printers.OfflineBanner";
        public const string OfflineErrorFormat = "Printers.OfflineErrorFormat";
        public const string PrefsButton = "Printers.PrefsButton";
        public const string PrefsTooltip = "Printers.PrefsTooltip";
        public const string PropsButton = "Printers.PropsButton";
        public const string PropsTooltip = "Printers.PropsTooltip";
        public const string ScanButton = "Printers.ScanButton";
        public const string VirtualBadge = "Printers.VirtualBadge";
        public const string WindowTitle = "Printers.WindowTitle";
    }

    public static class Range
    {
        public const string ErrorDetail = "Range.ErrorDetail";
        public const string FormatHint = "Range.FormatHint";
        public const string PreviewWillPrint = "Range.PreviewWillPrint";
        public const string Prompt = "Range.Prompt";
        public const string WindowTitle = "Range.WindowTitle";
        public const string WindowTitleWithFile = "Range.WindowTitleWithFile";
    }

    public static class Settings
    {
        public const string AdvancedIntro = "Settings.AdvancedIntro";
        public const string ApplyBtnDefault = "Settings.ApplyBtnDefault";
        public const string ApplyBtnTarget = "Settings.ApplyBtnTarget";
        public const string ApplyButton = "Settings.ApplyButton";
        public const string AutoOrientationCheck = "Settings.AutoOrientationCheck";
        public const string CoverPage = "Settings.CoverPage";
        public const string CoverPageHint = "Settings.CoverPageHint";
        public const string DeleteProfileBtn = "Settings.DeleteProfileBtn";
        public const string DriverTitle = "Settings.DriverTitle";
        public const string ErrorCopiesRange = "Settings.ErrorCopiesRange";
        public const string ErrorRangeSyntax = "Settings.ErrorRangeSyntax";
        public const string FitToPageWideCheck = "Settings.FitToPageWideCheck";
        public const string MergeHint = "Settings.MergeHint";
        public const string MergeIntoOne = "Settings.MergeIntoOne";
        public const string GroupPagesCopies = "Settings.GroupPagesCopies";
        public const string GroupPagesCopiesAdvanced = "Settings.GroupPagesCopiesAdvanced";
        public const string GroupPaperColor = "Settings.GroupPaperColor";
        public const string GroupPaperLayout = "Settings.GroupPaperLayout";
        public const string HintAutoOrientation = "Settings.HintAutoOrientation";
        public const string HintCollation = "Settings.HintCollation";
        public const string HintColor = "Settings.HintColor";
        public const string HintCopies = "Settings.HintCopies";
        public const string HintDriver = "Settings.HintDriver";
        public const string HintDuplex = "Settings.HintDuplex";
        public const string HintFitToPageWide = "Settings.HintFitToPageWide";
        public const string HintOrientation = "Settings.HintOrientation";
        public const string HintPaper = "Settings.HintPaper";
        public const string HintPaperSource = "Settings.HintPaperSource";
        public const string HintParity = "Settings.HintParity";
        public const string HintPerSheet = "Settings.HintPerSheet";
        public const string HintQuality = "Settings.HintQuality";
        public const string HintRangeSyntax = "Settings.HintRangeSyntax";
        public const string HintScale = "Settings.HintScale";
        public const string Introduction = "Settings.Introduction";
        public const string NoPrinterSelected = "Settings.NoPrinterSelected";
        public const string OptionCollation = "Settings.OptionCollation";
        public const string OptionColor = "Settings.OptionColor";
        public const string OptionCopies = "Settings.OptionCopies";
        public const string OptionDuplex = "Settings.OptionDuplex";
        public const string OptionOrientation = "Settings.OptionOrientation";
        public const string OptionPageRange = "Settings.OptionPageRange";
        public const string OptionPaper = "Settings.OptionPaper";
        public const string OptionPaperSource = "Settings.OptionPaperSource";
        public const string OptionParity = "Settings.OptionParity";
        public const string OptionPerSheet = "Settings.OptionPerSheet";
        public const string OptionQuality = "Settings.OptionQuality";
        public const string OptionScale = "Settings.OptionScale";
        public const string PrefsButton = "Settings.PrefsButton";
        public const string PreviewRangeAll = "Settings.PreviewRangeAll";
        public const string PreviewRangePrompt = "Settings.PreviewRangePrompt";
        public const string PreviewWillPrint = "Settings.PreviewWillPrint";
        public const string PrinterNotSelectedError = "Settings.PrinterNotSelectedError";
        public const string PrinterNotSelectedHint = "Settings.PrinterNotSelectedHint";
        public const string ProfileComboTooltip = "Settings.ProfileComboTooltip";
        public const string ProfileDeleted = "Settings.ProfileDeleted";
        public const string ProfileEmptyNameError = "Settings.ProfileEmptyNameError";
        public const string ProfileNameTooltip = "Settings.ProfileNameTooltip";
        public const string ProfileNone = "Settings.ProfileNone";
        public const string ProfileSaveError = "Settings.ProfileSaveError";
        public const string ProfileSaved = "Settings.ProfileSaved";
        public const string ProfileTitle = "Settings.ProfileTitle";
        public const string PropsButton = "Settings.PropsButton";
        public const string RangeAllRadio = "Settings.RangeAllRadio";
        public const string RangeBoxTooltip = "Settings.RangeBoxTooltip";
        public const string RangeCustomRadio = "Settings.RangeCustomRadio";
        public const string SaveProfileBtn = "Settings.SaveProfileBtn";
        public const string SaveProfileConfirmBtn = "Settings.SaveProfileConfirmBtn";
        public const string SheetHint = "Settings.SheetHint";
        public const string SheetOption = "Settings.SheetOption";
        public const string TabAdvanced = "Settings.TabAdvanced";
        public const string TabBasic = "Settings.TabBasic";
        public const string TitlePlural = "Settings.TitlePlural";
        public const string WatermarkOpacity = "Settings.WatermarkOpacity";
        public const string WatermarkOpacityHint = "Settings.WatermarkOpacityHint";
        public const string WatermarkText = "Settings.WatermarkText";
        public const string WatermarkTextHint = "Settings.WatermarkTextHint";
        public const string WindowTitle = "Settings.WindowTitle";
        public const string WindowTitlePlural = "Settings.WindowTitlePlural";
        public const string WindowTitleTarget = "Settings.WindowTitleTarget";
    }

    public static class Shell
    {
        public const string MenuText = "Shell.MenuText";
        public const string PrintTaskName = "Shell.PrintTaskName";
    }

    public static class Stop
    {
        public const string CancelBatch = "Stop.CancelBatch";
        public const string CancelConfirm = "Stop.CancelConfirm";
        public const string CancelRunning = "Stop.CancelRunning";
        public const string BatchCancelled = "Stop.BatchCancelled";
        public const string BatchNothingToCancel = "Stop.BatchNothingToCancel";
    }

    public static class Toast
    {
        public const string AddedWithSkip = "Toast.AddedWithSkip";
        public const string AppliedConfig = "Toast.AppliedConfig";
        public const string AppliedPageRangeCtx = "Toast.AppliedPageRangeCtx";
        public const string AppliedPagesPopup = "Toast.AppliedPagesPopup";
        public const string AppliedPagesPopupSheet = "Toast.AppliedPagesPopupSheet";
        public const string BatchDone = "Toast.BatchDone";
        public const string BatchStart = "Toast.BatchStart";
        public const string BatchStopped = "Toast.BatchStopped";
        public const string CtxPrintQueued = "Toast.CtxPrintQueued";
        public const string DedupSuffix = "Toast.DedupSuffix";
        public const string DefaultConfig = "Toast.DefaultConfig";
        public const string DeletedFiles = "Toast.DeletedFiles";
        public const string FileReloaded = "Toast.FileReloaded";
        public const string FilesAdded = "Toast.FilesAdded";
        public const string FilesAddedFromFolder = "Toast.FilesAddedFromFolder";
        public const string NoDuplicates = "Toast.NoDuplicates";
        public const string Paused = "Toast.Paused";
        public const string Resumed = "Toast.Resumed";
        public const string SkipSummarySome = "Toast.SkipSummarySome";
        public const string SkippedFormat = "Toast.SkippedFormat";
        public const string SkippedListJoin = "Toast.SkippedListJoin";
        public const string SkippedMissing = "Toast.SkippedMissing";
        public const string SkippedOnly = "Toast.SkippedOnly";
        public const string SkippedUnsupported = "Toast.SkippedUnsupported";
    }

    public static class Watch
    {
        public const string FileAdded = "Watch.FileAdded";
        public const string InfoNote = "Watch.InfoNote";
        public const string NoFolder = "Watch.NoFolder";
        public const string PrintedDetail = "Watch.PrintedDetail";
        public const string PrintedTitle = "Watch.PrintedTitle";
        public const string SelectFolder = "Watch.SelectFolder";
        public const string StatusActive = "Watch.StatusActive";
        public const string StatusInactive = "Watch.StatusInactive";
        public const string StatusWarning = "Watch.StatusWarning";
        public const string StopWatching = "Watch.StopWatching";
        public const string WindowTitle = "Watch.WindowTitle";
    }

}